name: Famfrpal
version: 1.0.0
author: xvojta_Nemo
description: Famfrpal epic plugin!
main: com.xvojta.famfrpal.Famfrpal
commands:
  fpstart:
    description: famfrpal start command
    usage: /<command>
  fpscore:
    description: famfrpal score edit.
    usage: /<command> [set | add] [player]

  permissions:
    fp.*:
      description: Famfrpals permissions
      children:
        team1:
          default: false
        team2:
          default: false
        team3:
          default: false
        team4:
          default: false
        team5:
          default: false
        team6:
          default: false
        team7:
          default: false
        team8:
          default: false

